"""Synthetic but realistic (messy) Indian health-facility records for local dev.

These mirror the provided 10k dataset's schema (name, state, city, postcode,
latitude, longitude, numberDoctors, capacity, yearEstablished + the noisy
evidence fields: description, capability, procedure, equipment, specialties,
source_urls). They deliberately include the hard cases the judges care about:
negation ("no ICU, refer"), broken equipment ("ventilator out of order"),
partial capability ("blood storage unit, not full blood bank"), inconsistent
casing, and sparse / missing fields. Swap for the real dataset via env (see data.py).
"""
import pandas as pd

_ROWS = [
    {
        "facility_id": "IND-0001", "name": "District Hospital Nashik",
        "state": "Maharashtra", "city": "Nashik", "postcode": "422001",
        "latitude": 19.9975, "longitude": 73.7898,
        "numberDoctors": 45, "capacity": 320, "yearEstablished": 1965,
        "description": "District Hospital providing comprehensive secondary care, including 24x7 casualty and emergency, operation theatres, a maternity ward with labour room, and a functional blood bank.",
        "capability": "ICU; Maternity; Emergency; Blood Bank; General Surgery",
        "procedure": "Caesarean section; major surgery; institutional delivery; blood transfusion",
        "equipment": "Ventilators; X-Ray; USG; CT scan; laboratory",
        "specialties": "General Medicine; Obstetrics & Gynaecology; General Surgery",
        "source_urls": "https://example.gov.in/nashik-dh",
    },
    {
        "facility_id": "IND-0002", "name": "PHC Khedgaon",
        "state": "Maharashtra", "city": "Khedgaon", "postcode": "422206",
        "latitude": 19.71, "longitude": 73.99,
        "numberDoctors": 1, "capacity": 6, "yearEstablished": 2002,
        "description": "Primary Health Centre offering outpatient care, immunization and normal deliveries. No ICU and no operation theatre; serious and surgical cases are referred to the district hospital.",
        "capability": "Normal delivery; antenatal care; immunization",
        "procedure": "Institutional delivery (normal)",
        "equipment": "",
        "specialties": "General Medicine",
        "source_urls": "https://example.gov.in/phc-khedgaon",
    },
    {
        "facility_id": "IND-0003", "name": "CHC Sinnar",
        "state": "Maharashtra", "city": "Sinnar", "postcode": "422103",
        "latitude": 19.85, "longitude": 74.00,
        "numberDoctors": 6, "capacity": 30, "yearEstablished": 1988,
        "description": "Community Health Centre with 24x7 casualty and a labour room.",
        "capability": "Emergency; Maternity; Minor surgery",
        "procedure": "Minor OT procedures",
        "equipment": "X-Ray. ICU under construction. Ventilator out of order. Blood storage unit (not a full blood bank).",
        "specialties": "General Surgery; Obstetrics",
        "source_urls": "",
    },
    {
        "facility_id": "IND-0004", "name": "Apollo Cancer Centre",
        "state": "Karnataka", "city": "Bengaluru", "postcode": "560076",
        "latitude": 12.97, "longitude": 77.64,
        "numberDoctors": 60, "capacity": 150, "yearEstablished": 2010,
        "description": "Tertiary oncology centre offering chemotherapy, radiotherapy and oncosurgery with a dedicated ICU.",
        "capability": "Oncology; ICU; Chemotherapy; Radiotherapy",
        "procedure": "Chemotherapy; radiation therapy; oncosurgery; tumour resection",
        "equipment": "Linear accelerator; CT scan; MRI; ventilators",
        "specialties": "Medical Oncology; Surgical Oncology; Radiation Oncology",
        "source_urls": "https://example.com/apollo-cancer",
    },
    {
        "facility_id": "IND-0005", "name": "SDH Malegaon",
        "state": "Maharashtra", "city": "Malegaon", "postcode": "423203",
        "latitude": 20.55, "longitude": 74.53,
        "numberDoctors": 20, "capacity": 100, "yearEstablished": 1992,
        "description": "Sub-district hospital. icu AVAILABLE; OT FUNCTIONAL; bloodbank NO.",
        "capability": "MATERNITY; caesarean; emergency",
        "procedure": "lscs; normal delivery",
        "equipment": "x-ray, usg, laboratory",
        "specialties": "obg; surgery",
        "source_urls": "",
    },
    {
        "facility_id": "IND-0006", "name": "Rural Hospital Trimbak",
        "state": "Maharashtra", "city": "Trimbak", "postcode": "422212",
        "latitude": 19.93, "longitude": 73.53,
        "numberDoctors": 5, "capacity": 50, "yearEstablished": 1979,
        "description": "Rural hospital. Emergency services not functional after 8 pm. Maternity referred to FRU at district. Operation theatre present but no anaesthetist.",
        "capability": "Outpatient; inpatient",
        "procedure": "",
        "equipment": "X-Ray",
        "specialties": "General Medicine",
        "source_urls": "",
    },
    {
        "facility_id": "IND-0007", "name": "Trauma Care Centre Sangamner",
        "state": "Maharashtra", "city": "Sangamner", "postcode": "422605",
        "latitude": 19.57, "longitude": 74.21,
        "numberDoctors": 12, "capacity": 40, "yearEstablished": 2015,
        "description": "Dedicated trauma centre with 24x7 emergency and accident care and a critical care unit staffed round the clock.",
        "capability": "Trauma; Emergency; ICU; Orthopaedics",
        "procedure": "Polytrauma management; major surgery",
        "equipment": "Ventilators; CT scan; X-Ray; blood bank",
        "specialties": "Orthopaedics; General Surgery; Emergency Medicine",
        "source_urls": "https://example.gov.in/trauma-sangamner",
    },
    {
        "facility_id": "IND-0008", "name": "PHC Igatpuri",
        "state": "Maharashtra", "city": "Igatpuri", "postcode": "422403",
        "latitude": 19.69, "longitude": 73.56,
        "numberDoctors": 1, "capacity": 4, "yearEstablished": 2008,
        "description": "Primary Health Centre. Immunization and OPD only.",
        "capability": "Immunization; OPD",
        "procedure": "",
        "equipment": "",
        "specialties": "",
        "source_urls": "",
    },
    {
        "facility_id": "IND-0009", "name": "Wellcare Maternity & Newborn Home",
        "state": "Telangana", "city": "Hyderabad", "postcode": "500032",
        "latitude": 17.39, "longitude": 78.49,
        "numberDoctors": 8, "capacity": 25, "yearEstablished": 2012,
        "description": "Maternity home with obstetric care and a special newborn care unit (SNCU). No adult ICU; critical adults are referred.",
        "capability": "Maternity; NICU; Antenatal",
        "procedure": "Institutional delivery; LSCS; neonatal resuscitation",
        "equipment": "Radiant warmer; phototherapy; ultrasound",
        "specialties": "Obstetrics & Gynaecology; Neonatology",
        "source_urls": "https://example.com/wellcare",
    },
    {
        "facility_id": "IND-0010", "name": "CHC Deola",
        "state": "Maharashtra", "city": "Deola", "postcode": "423102",
        "latitude": 20.73, "longitude": 74.06,
        "numberDoctors": 4, "capacity": 30, "yearEstablished": 1990,
        "description": "Community Health Centre. Casualty and labour room available. General surgeon visits twice a week.",
        "capability": "Emergency; Maternity; Surgery",
        "procedure": "General surgery (visiting surgeon)",
        "equipment": "X-ray functional. ICU nil. Blood bank nil.",
        "specialties": "General Surgery",
        "source_urls": "",
    },
    {
        "facility_id": "IND-0011", "name": "Lifeline Multispecialty",
        "state": "Maharashtra", "city": "Pune", "postcode": "411001",
        "latitude": 18.52, "longitude": 73.85,
        "numberDoctors": 90, "capacity": 180, "yearEstablished": 2005,
        "description": "Round the clock emergency, ICU and HDU, cardiac and cancer surgery, maternity, blood bank and dialysis.",
        "capability": "Emergency; ICU; Oncology; Maternity; Blood Bank",
        "procedure": "Chemotherapy; major surgery; caesarean; dialysis",
        "equipment": "MRI; CT scan; X-Ray; USG; ventilators; ECG",
        "specialties": "Cardiology; Oncology; Critical Care; Obstetrics",
        "source_urls": "https://example.com/lifeline",
    },
    {
        "facility_id": "IND-0012", "name": "Sub Centre Pimpalgaon",
        "state": "Maharashtra", "city": "Pimpalgaon", "postcode": "422209",
        "latitude": 20.17, "longitude": 73.98,
        "numberDoctors": None, "capacity": None, "yearEstablished": None,
        "description": "Sub Centre. ANM available for antenatal checkups and immunization. No inpatient facility.",
        "capability": "Antenatal; immunization",
        "procedure": "",
        "equipment": "",
        "specialties": "",
        "source_urls": "",
    },
]


def load_sample() -> pd.DataFrame:
    return pd.DataFrame(_ROWS)
